project/client_test/urls.py
from django.urls import path
from . import views

app_name = 'client_test'

urlpatterns = [
    path('', views.home, name='home'),
    path('get/user/details', views.client_details, name='client_details'),
	path('user/new', views.user_new, name='user_new'),
    path('user/update', views.save_updated_user, name='save_updated_user'),
    path('user/get_updated_user/<int:pk>',views.get_updated_user, name='get_updated_user'),
    path('user/delete/<int:pk>', views.delete_user, name='delete_user'),
    path('ajax/getStates',views.get_states, name='get_states'),
    path('ajax/getCities',views.get_cities, name='get_cities'),
]

project/python_test/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
	path('', include('client_test.urls')),
    path('admin/', admin.site.urls),
]

project/client_test/models.py
from django.db import models


# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Client(models.Model):
    client_name = models.CharField(max_length=20, unique=True, help_text="Client name should be unique.")
    contact_name = models.CharField(max_length=200, help_text="Please! Enter your full name.")
    birth_date = models.DateField()
    email_address = models.EmailField()
    area_code = models.PositiveSmallIntegerField()
    phone_number = models.PositiveIntegerField()
    mobile_number = models.PositiveIntegerField(max_length=10, blank=True)
    street_name = models.CharField(max_length=200, blank=True)
    suburb = models.CharField(max_length=100)
    postcode = models.PositiveIntegerField(max_length=9)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.client_name

project/client_test/forms.py
from django import forms
from .models import Client, City, State, Country
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime

current_year = datetime.datetime.now().year


def validate_min(value):
    if len(str(value)) < 10 or len(str(value)) > 10:
        raise ValidationError(
            _('Phone number : %(value)s cannot be less or greater than 10.'),
            params={'value': value},
        )


def validate_postal_code(value):
    if len(str(value)) > 10:
        raise ValidationError(_('Postal Code : %(value)s cannot be greater than 10 digit length.'),
                              params={'value': value}, )


class Client_DetailsForm(forms.ModelForm):
    area_code = forms.IntegerField()
    phone_number = forms.IntegerField()
    mobile_number = forms.IntegerField(validators=[validate_min])
    postcode = forms.IntegerField(validators=[validate_postal_code])
    birth_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"),years=(range(current_year - 100,current_year + 1 )),),)


    class Meta:
        model = Client
        fields = (
        'client_name', 'contact_name', 'birth_date', 'email_address', 'area_code', 'phone_number', 'mobile_number',
        'street_name', 'suburb', 'postcode', 'country', 'state', 'city',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()
        self.fields['state'].queryset = State.objects.none()

        if 'country' in self.data:
            if 'state' in self.data:
                try:
                    state_id = int(self.data.get('state'))
                    self.fields['city'].queryset = City.objects.filter(state=state_id).order_by('name')
                except (ValueError, TypeError):
                    pass
            try:
                country_id = int(self.data.get('country'))
                self.fields['state'].queryset = State.objects.filter(country=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')
            self.fields['state'].queryset = self.instance.country.city_set.order_by('name')

class Client_DetailsUpdateForm(forms.ModelForm):
    client_name = forms.CharField(disabled=True)
    area_code = forms.IntegerField()
    phone_number = forms.IntegerField()
    mobile_number = forms.IntegerField(validators=[validate_min])
    postcode = forms.IntegerField(validators=[validate_postal_code])
    birth_date = forms.DateField(widget=forms.SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"),years=(range(current_year - 100,current_year + 1)),),)

    class Meta:
        model = Client
        fields = (
        'client_name', 'contact_name', 'birth_date', 'email_address', 'area_code', 'phone_number', 'mobile_number',
        'street_name', 'suburb', 'postcode', 'country', 'state', 'city',)

project/client_test/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Client, Country, State, City
from django.db.models import Q
from .forms import Client_DetailsForm, Client_DetailsUpdateForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
from django.contrib import messages


def getPaginator(request, object):
    page = request.GET.get('page', 1)
    paginator = Paginator(object, 5)
    try:
        clients = paginator.page(page)
    except PageNotAnInteger:
        clients = paginator.page(1)
    except EmptyPage:
        clients = paginator.page(paginator.num_pages)
    return clients


def get_states(request):
    country_id = request.GET.get('country')
    states = State.objects.filter(country=country_id).order_by('name')
    return render(request, 'client_test/states.html', {'states': states})


def get_cities(request):
    state_id = request.GET.get('state')
    cities = City.objects.filter(state=state_id).order_by('name')
    return render(request, 'client_test/cities.html', {'cities': cities})

def home(request):
    client_detail = Client.objects.order_by('client_name')
    clients = getPaginator(request, client_detail)
    return render(request,'client_test/client_details.html',{'client_details':clients})


def client_details(request):
    data = dict()
    field_value = request.GET.get('value_placeholder')
    print(field_value)

    if field_value:
        clients = Client.objects.filter(Q(client_name__contains=field_value) | Q(email_address__contains=field_value) | Q(phone_number__contains=field_value) | Q(suburb__contains=field_value) | Q(mobile_number__contains=field_value))

        context = {'client_details': clients}
        data['html_form'] = render_to_string('client_test/get_client_details.html',context,request=request)

        return JsonResponse(data)

    else:
        client_detail = Client.objects.order_by('client_name')
        clients = getPaginator(request, client_detail)
        context = {'client_details': clients}
        data['html_form'] = render_to_string('client_test/get_client_details.html',context,request=request)

        return JsonResponse(data)




def save_updated_user(request):
    data = dict()

    if request.method == 'POST':

        client = get_object_or_404(Client, email_address=request.POST.get("email_address"))
        form = Client_DetailsUpdateForm(request.POST, instance=client)
        if form.is_valid():

            form.save()
            return redirect('/')
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string('client_test/user_update_add.html',
                                         context,
                                         request=request
                                         )
    return JsonResponse(data)


def get_updated_user(request, pk):
    data = dict()
    client = get_object_or_404(Client, pk=pk)
    form = Client_DetailsUpdateForm(instance=client)


    context = {'form': form}
    data['html_form'] = render_to_string('client_test/user_update_add.html',
                                         context,
                                         request=request
                                         )
    return JsonResponse(data)

    # args = {}
    # if request.method == 'POST':
    #     client = get_object_or_404(Client, email_address=request.POST.get("email_address"))
    #     form = Client_DetailsUpdateForm(request.POST, instance=client)
    #     if form.is_valid():
    #         form.save()
    #         messages.success(request, 'User Updated Successfully.')
    #         return redirect('/')
    # else:
    #     form = Client_DetailsUpdateForm()
    #
    # args['form'] = form
    # return render(request, 'client_test/update_user.html', args)


def user_new(request):
    data = dict()

    if request.method == 'POST':

        print(request.POST)
        form = Client_DetailsForm(request.POST)
        if form.is_valid():
            #form.cleaned_data()
            form.save()
            return redirect('/')
        else:
            data['form_is_valid'] = False
    else:
        form = Client_DetailsForm()

    context = {'form': form}
    data['html_form'] = render_to_string('client_test/user_update_add.html',
                                         context,
                                         request=request
                                         )
    return JsonResponse(data)


def delete_user(request, pk):

    try:
        client = get_object_or_404(Client, pk=pk)
        client.delete()
        messages.success(request, 'User Deleted Successfully.')
        return redirect('/')
    except Exception:
        raise

project/client_test/templates/client_test/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Doyenhub Software Solutions</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static 'css/crudfile.css' %}">

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
    <script src="{% static 'js/crudfile.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  </head>
    <body>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'client_test:client_details' %}">SimpleCRUD</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'client_test:client_details' %}">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  {% block content %}
    {% endblock %}
</div>

            

           
</body>
</html>

project/client_test/templates/client_test/cities.html
<option value="">--Select Option--</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

project/client_test/templates/client_test/client_details.html
{% extends "client_test/base.html" %}
{% block content %}
<div >
    {% if messages %}
        <div class="messages alert alert-success">
            {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <div id="Message">
        <p></p>
    </div>
    <div class="well well-sm">
        <h3>Client Details</h3>
    </div>
    <div>
        <div>
            <div style="width: 120px;float: right;">

                <a href="{% url 'client_test:user_new' %}" data-toggle="modal" data-target="#myModal"
                   style="color:white;" class="btn btn-primary" id="js-add-button">
                    <span class="glyphicon glyphicon-plus"></span> Add User</a>

            </div>
            <br>
            <form action="{% url 'client_test:client_details' %}" method="GET" id="js-search-form">
                {% csrf_token %}
                <div class="input-group" style="width: 500px;float: left;bottom: 20px;height: 10px;">
                    <input type="search" class="form-control"
                           placeholder="Enter username, email, suburb or phone number...." name="value_placeholder">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="button" id="js-search-button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br>
    <div id="js-get-table">

        <table class="table tablesorter" id="myTable">
        <thead >
        <tr>
            <th >User Name </th>
            <th >Full Name </th>
            <th >Birth Date </th>
            <th >Email </th>
            <th >Phone Number </th>
            <th >Mobile Number </th>
            <th >Address </th>
            <!--&lt;!&ndash;<th >Postal </th>&ndash;&gt;-->
            <!--&lt;!&ndash;<th >City </th>&ndash;&gt;-->
            <!--&lt;!&ndash;<th >State </th>&ndash;&gt;-->
            <!--&lt;!&ndash;<th >Country </th>&ndash;&gt;-->
        </tr>
        </thead>
        <tbody id="get_table_body">
        {% for details in client_details %}
        <tr>
            <td>{{ details.client_name }}</td>
            <td class="align-middle">{{ details.contact_name }}</td>
            <td class="align-middle">{{ details.birth_date }}</td>
            <td class="align-middle">{{ details.email_address }}</td>
            <td class="align-middle">{{ details.area_code }} - {{ details.phone_number }}</td>
            <td class="align-middle">{{ details.mobile_number }}</td>
            <td class="align-middle">{{ details.street_name }} , {{ details.suburb }} , {{ details.postcode }} , {{ details.city }} , {{ details.state }} ,{{ details.country }}</td>

            <td class="align-middle">
                <span data-toggle="tooltip"  title="Click to Edit" >
                    <a href="{% url 'client_test:get_updated_user' pk=details.pk %}"  id="js-editUser" data-toggle="modal" data-target="#myModalUpdate">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                </span>
            </td>
            <td class="align-middle">
                <a href="{% url 'client_test:delete_user' pk=details.pk %}" data-toggle="tooltip" title="Delete" id="js-deleteUser">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if client_details.has_other_pages %}
    <ul class="pagination">
        {% if client_details.has_previous %}
        <li><a href="?page={{ client_details.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in client_details.paginator.page_range %}
        {% if client_details.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if client_details.has_next %}
        <li><a href="?page={{ client_details.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}

    </div>
    <!---->
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->

  </div>
</div>

<div id="myModalUpdate" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->

  </div>
</div>
</body>
{% endblock %}

project/client_test/templates/client_test/get_client_details.html
        {% if client_details %}
        {% for details in client_details %}
        <tr>
            <td>{{ details.client_name }}</td>
            <td class="align-middle">{{ details.contact_name }}</td>
            <td class="align-middle">{{ details.birth_date }}</td>
            <td class="align-middle">{{ details.email_address }}</td>
            <td class="align-middle">{{ details.area_code }} - {{ details.phone_number }}</td>
            <td class="align-middle">{{ details.mobile_number }}</td>
            <td class="align-middle">{{ details.street_name }} , {{ details.suburb }} , {{ details.postcode }} , {{ details.city }} , {{ details.state }} ,{{ details.country }}</td>

            <td class="align-middle">
                <span data-toggle="tooltip"  title="Click to Edit" >
                    <a href="{% url 'client_test:get_updated_user' pk=details.pk %}"  id="js-editUser" data-toggle="modal" data-target="#myModalUpdate">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                </span>
            </td>
            <td class="align-middle">
                <a href="{% url 'client_test:delete_user' pk=details.pk %}" data-toggle="tooltip" title="Delete" id="js-deleteUser">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </td>
        </tr>
        {% endfor %}
        {% endif %}

project/client_test/templates/client_test/states.html
<option value="">--Select Option--</option>
{% for state in states %}
<option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}

project/client_test/templates/client_test/update_user.html
{% extends 'client_test/base.html' %}

{% block content %}

<div id="Message">
        <p></p>
    </div>
<h1>Update User</h1>
<form method="POST" action="{% url 'client_test:save_updated_user' %}">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr><td><input type="hidden" name="client_pk" id="client_pk" value="{{ pk }}"></td></tr>
    </table>
    <input type="submit" class="btn btn-primary" value="Save">
</form>
{% endblock %}